name: build-files
on: [push]
jobs:
  build-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
      - run: zip -r ShortCutExtension.zip dist