name: Pull Request

on: pull_request

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install modules
        run: npm install
      - name: Check code formatting
        run: |
          npm run lint
      - name: Run unit test
        run: npm run test