name: Pull Request

on: pull_request

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install modules
        run: npm install --legacy-peer-deps
      - name: Check code formatting
        run: |
          npm run lint
      - name: Run unit test
        run: npm run test
